# Form implementation generated from reading ui file 'C:\Users\ADMIN\BAOHUY\JulepAI_Application\ui\ApplicationWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 661)
        MainWindow.setStyleSheet("font-size: 20px;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 0, 431, 41))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 761, 111))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(80, 40, 71, 31))
        self.label_2.setObjectName("label_2")
        self.lineEditTopic = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditTopic.setGeometry(QtCore.QRect(180, 30, 481, 51))
        self.lineEditTopic.setObjectName("lineEditTopic")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 180, 761, 411))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEditOutput = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.textEditOutput.setGeometry(QtCore.QRect(20, 40, 721, 291))
        self.textEditOutput.setObjectName("textEditOutput")
        self.pushbuttonGenerate = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushbuttonGenerate.setGeometry(QtCore.QRect(290, 350, 171, 41))
        self.pushbuttonGenerate.setObjectName("pushbuttonGenerate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Generate Story by AI Agent</span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Enter topic"))
        self.label_2.setText(_translate("MainWindow", "Topic:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output"))
        self.pushbuttonGenerate.setText(_translate("MainWindow", "Generate"))
